name: Config API
on: [push]

jobs:
   test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt -r requirements/requirements-dev.txt
      - name: Run tests
        run: |
          catalyst-dl run -C configs/test_config.yml --verbose
      - name: Clear logs
        run: rm -rf logs